package com.djava.ch10_2_exceptionTest;

public class ThrowsTest {
	
	public void test(int b) throws Exception{ // throw 호출하는 쪽에서 책임져라
		int a = 10;
		int result = a / b;
				
	}
	
	
	
}
